[tool.ruff]
src = ["cmk", "tests"]
target-version = "py311"
ignore = [
    "E402",  # module level import not on top of the file
    "E501",  # line too long, 100s of fails. Fixable.
    "E731",  # Do not assign a `lambda` expression, use a `def`
    "E741",  # amgiguous variable name (l, x, etc.)
    "E713",  # Test for membership should be `not in`
    "E999",  # SyntaxError, all due to missing "match" support in ruff. See: https://github.com/charliermarsh/ruff/issues/282

    "S101",  # assert detected

    # Ignored in .flake8 but not here.
    # F403 undefined imports, all are fixed now, but we shouldn't add new ones.
    # F405 are * imports. We shouldn't do those.
]
select = ["E", "F", "YTT"]
# Interesting to enable:
#   "RUF" - Remove unused "noqa" directives from the code, etc.
#   "TRY" - remove those "raise Exception" calls. 1688 failures.
#   "G"  - wrong logging.log formattion! 107 failures
#   "S" - emulate bandit. 12993 errors detected. Ignoring complaints about asserts, 335 failures remain.
#   "PGH" - complain about blanket "type: ignore" without specifics.
#   "T20" - complain about print found. 217 "failures" found. Needs some rework first!
#   "DTZ" - disallows datetime objects without timezone, 254 failures.
#   "UP" - emulate pyupgrade. 3024 failures, 3005 fixable automatically.

#   "C4" - simplify comprehensions, 164 failures, 138 auto fixable
#   "B" - bugbear, 756 failures, 71 auto fixable
#   "ERA" - commented out code, 1717 failures, 1717 auto fixable
#   "PL" - impersonate PyLint. 2819 failures, 1 auto fixable.
#   "ARG" - unused arguments, 3358 failures
#   "I" - replaces isort, but doesn't honor isort disable annotation yet, only "noqa: I001"
#   "D" - enforces docstring writing style. Ignore "D10,D4" for now.
#   "COM" - enforce trailing comma. Lots of matches.
unfixable = [
    "F401",  # pylint: disable=unused-import. Clean up by hand.
]
[per-file-ignores]
"cmk/gui/config.py" = [
    "F403",
    "F405",
]
[flake8-annotations]
suppress-dummy-args = true
[mccabe]
max-complexity = 15


[tool.isort]
known_testlib = "tests.testlib"
known_compositiontests = "tests.composition"
known_unittests = "tests.unit"
known_livestatus = "livestatus"
known_omd = "omdlib"
known_cmk_utils = "cmk.utils"
known_cmk_automations = "cmk.automations"
known_cmk_base = "cmk.base"
known_cmc_proto = "cmc_proto"
known_cmk_ec = "cmk.ec"
known_cmk_gui = "cmk.gui"
known_cmk_cee = "cmk.cee.dcd,cmk.cee.liveproxy,cmk.cee.mknotifyd"
known_cmk_notification_plugins = "cmk.notification_plugins"
known_cmk_snmplib = "cmk.snmplib"
known_cmk_fetchers = "cmk.fetchers"
known_cmk_checkers = "cmk.checkers"
known_first_party = "cmk"

# Order sections according to our layering.
sections = """FUTURE,STDLIB,THIRDPARTY,CMC_PROTO,TESTLIB,COMPOSITIONTESTS,UNITTESTS,LIVESTATUS,OMD,
CMK_UTILS,CMK_AUTOMATIONS,CMK_SNMPLIB,CMK_FETCHERS,CMK_CHECKERS,CMK_BASE,CMK_EC,CMK_GUI,CMK_CEE,
CMK_NOTIFICATION_PLUGINS,FIRSTPARTY,LOCALFOLDER"""

# configuration options compatible with black
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
order_by_type = "False"
line_length = 100
py_version = "311"


[tool.black]
line-length = 100
target-version = ['py311']


# NOTE: Keep this is sync with mypy-raw.ini!
# The number of errors/files below are just a snapshot to give a rough idea. In
# addition, a single cause can imply multiple symptoms, so these numbers have to
# be taken with a grain of salt...
[tool.mypy]
plugins = ["pydantic.mypy"]
# When all of these are true, we can enable --strict
check_untyped_defs = true
disallow_any_generics = false  # 1904 errors in 507 files
disallow_incomplete_defs = true
disallow_subclassing_any = false  # 11 errors in 10 files
disallow_untyped_calls = false  # 6427 errors in 1077 files
disallow_untyped_decorators = true
disallow_untyped_defs = false  # 6738 errors in 1571
no_implicit_optional = true
no_implicit_reexport = false  # 3026 errors in 1213 files
strict_concatenate = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = false  # 821 errors in 304 files
warn_unused_configs = true
warn_unused_ignores = false  # 1324 errors in 1281 files
# Miscellaneous stuff not in --strict
disallow_any_decorated = false  # 3433 errors in 997 files
disallow_any_explicit = false  # 2854 errors in 836 files
disallow_any_expr = false  # 112427 errors in 3304 files
disallow_any_unimported = false  # 317 errors in 47 files
warn_unreachable = false  # 240 errors in 133 files

[[tool.mypy.overrides]]
module = [
    "cmk.gui.mobile.views",
    "cmk.gui.views.layout",
    "cmk.gui.views.painter",
    "cmk.gui.background_job",
    "cmk.notification_plugins.*",
    "tests.gui_e2e.*",
    "tests.testlib.playwright.*",
    "tests.unit.cmk.ec.*",
    "tests.testlib.event_console",
]
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
